### ISSUE TITLE
Notice: You are Blocked!

### ISSUE THREAD

**Issue by awsassets** [Anduin2017/CameraVoyeur#21]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/59461072/154882454-f19b5460-6b3e-4bcf-a557-f8a51b7db7c0.png">

**Comment by MBRjun** [comment]
草 什么玩意 我watch了这个仓库 收到这个Issue的邮件 我直接迷惑

**Comment by MBRjun** [comment]
电信诈骗这活还是你会整
